spring.application.name=spring-boot-project

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/hospitalDB/
spring.datasource.username=
spring.datasource.password=

#various types are create-drop(will create and drop once the app is stopped),
# create(it will not drop the db once the app is stopped, rather it will drop and create new db when the app starts),
# update(whenever we make any changes in the application regarding DB it will update the changes in the DB )
# usually only 2 things are done in prod: validate(it will validate the relationship in prod and the objects which we are getting from code belongs to same entities or ddl, the app will crash if not validated)
# or none
spring.jpa.hibernate.ddl-auto=update
#in prod this will be usually false
spring.jpa.show-sql=true
#for formatting
spring.jpa.properties.hibernate.format_sql=false
